import { Toaster } from "react-hot-toast";
import { ReactQueryProvider } from "@/components/ReactQueryProvider";
import { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Project Management Tool",
  description: "Generated by Antu_das",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ReactQueryProvider>
      <html lang="en">
        <body>
          <Toaster position="top-center" />
          {children}
        </body>
      </html>
    </ReactQueryProvider>
  );
}